# set variables
- name: "Set script variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ SERVICE }}.yml"
    - default.yml


- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive


- name: Packages
  include_tasks: packages.yml



# setup /etc/hosts
- include_tasks: add-host.yml
  vars:
    var_host: "{{ host }}"
    var_hostname: "{{ hostname }}"



# setup /etc/hostname
- include_tasks: add-hostname.yml
  vars:
    var_hostname: "{{ hostname }}"



# Setup firewalld
- name: Open ports - Firewalld
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ ports }}"



- name: Configuration
  include_tasks: config.yml



- name: Enable services
  ansible.builtin.debug: 
    msg: "Restarting services"
  notify: 
    - enable and restart elasticsearch
    - enable and restart daemon-reload