- name: Add docker repo
  ansible.builtin.shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose


- name: Change mod of docker-compose directory
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    state: directory
    mode: '0755'



