- name: "Set environment variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ENV }}.yml"
    - default.yml

- name: "Set backup dir name"
    set_fact:
      backup_dir: "/var/lib/{{ DB_NAME }}/backups"
