- name: enable and restart daemon-reload
  ansible.builtin.service: 
    name: daemon-reload 
    state: restarted 
    enabled: yes
- name: enable and restart mysqld
  ansible.builtin.service: 
    name: mysqld 
    state: restarted 
    enabled: yes
- name: enable and restart httpd
  ansible.builtin.service: 
    name: httpd 
    state: restarted 
    enabled: yes

