- name: Msg inicial
  ansible.builtin.debug:
    msg: "Usando arquivo de variáveis {{ ansible_facts['os_family'] }}.yml para instalação"

- name: os
  set_fact:
    os : "{{ ansible_facts['os_family'] }}.yml"


- name: Variáveis
  include_vars: "{{ os }}"


- name: Dependências
  include_tasks: packages.yml


- name: Configura Mysql
  include_tasks: config.yml



