- name: Update
  ansible.builtin.shell: dnf update -y
  when: installer == "dnf"


- name: Install packages using dnf
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"
  when: installer == "dnf"



- name: Install packages using yum
  ansible.builtin.yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"
  when: installer == "yum"



- name: Install packages using apt
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"
  when: installer == "apt"



- name: Install PyMySQL
  ansible.builtin.pip:
    name: PyMySQL



- name: Start mysql
  ansible.builtin.service:
    name: mysqld
    state: started



- name: Restart services
  ansible.builtin.debug: 
    msg: "Restarting services"
  notify: 
    - enable and restart mysqld
    - enable and restart daemon-reload

