- name: Update
  ansible.builtin.shell: "{{ installer }}" update -y


- name: Install packages using dnf
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"
  when: installer = "dnf"



- name: Install packages using yum
  ansible.builtin.yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"
  when: installer = "yum"



- name: Install packages using apt
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"
  when: installer = "apt"
