- name: "Dump POSTGRESQL DB from a docker container"
  set_fact:
    password_arg: "-W {{ password }}"
  set_fact:
    password_arg: ""
  when: password|length == 0
  community.docker.docker_container_exec:
    container: "{{ db_container }}"
    command: /bin/bash -c "pg_dumpall -c -U {{ username }} {{ password_arg }} --all-databases > {{ target_file }}"
  args:
    chdir: "{{ directory }}"


    